# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

# Trajectory Controllers ---------------------------------------
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint1: {trajectory: 0.1, goal: 0.1}
    joint2: {trajectory: 0.1, goal: 0.1}
    joint3: {trajectory: 0.1, goal: 0.1}
    joint4: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_position:
  type: effort_controllers/JointPositionController
  joint: gripper
  pid: {p: 10.0, i: 0.0, d: 1.0}

gripper_sub_position:
  type: effort_controllers/JointPositionController
  joint: gripper_sub
  pid: {p: 10.0, i: 0.0, d: 1.0}

# hand_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - gripper
#     - gripper_sub
#   constraints:
#     goal_time: 0.6
#     stopped_velocity_tolerance: 0.05
#     gripper: {trajectory: 0.1, goal: 0.1}
#     gripper_sub: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10
